version: '3.8'

services:
  # PostgreSQL Сервис
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - algoforge-net

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/src:/app/src
    depends_on:
      - auth-service
      # - task-service
      # - testrunner-service
    networks:
      - algoforge-net

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    # ports:
    #   - "8081:8081"
    volumes:
      - ./auth-service/src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_DATASOURCE_HIKARI_AUTO-COMMIT: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_PROVIDER_DISABLES_AUTOCOMMIT: "true"
    networks:
      - algoforge-net

  # Task Service
  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    container_name: task-service
    # ports:
    #   - "8082:8082"
    volumes:
      - ./task-service/src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: task
    networks:
      - algoforge-net


  contest-service:
    build:
      context: .
      dockerfile: contest-service/Dockerfile
    container_name: contest-service
    # ports:
    #   - "8083:8083"
    volumes:
      - ./contest-service/src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - algoforge-net

  admin-service:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    container_name: admin-service
    # ports:
    #   - "8084:8084"
    volumes:
      - ./admin-service/src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
      - auth-service
      - task-service
      - contest-service
    networks:
      - algoforge-net
  # Test Runner Service
  testrunner-service:
    build:
      context: .
      dockerfile: testrunner-service/Dockerfile
    container_name: testrunner-service
    # ports:
    #   - "8090:8090"
    volumes:
      - ./testrunner-service/src:/app/src
    networks:
      - algoforge-net
  solution-service:
    build:
      context: .
      dockerfile: solution-service/Dockerfile
    container_name: solution-service
    # ports:
    #   - "8099:8099"
    volumes:
      - ./solution-service/src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - algoforge-net

networks:
  algoforge-net:
    driver: bridge
